spring:
  application:
    name: DigitalWallet

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/digital_wallet?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
